# Generated by Django 6.0.6 on 2026-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
