# Generated by Django 6.0.6 on 2026-06-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_must_change_password_users_password_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='current_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
