# Generated by Django 6.0.6 on 2026-06-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_current_token_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='current_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
