# Generated by Django 6.0.6 on 2026-06-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_current_token_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('listar_usuarios', 'Listar usuarios'), ('generar_reporte_usuarios', 'Generar reporte usuarios')]},
        ),
    ]
