# Generated by Django 6.0.6 on 2026-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
