# Generated by Django 6.0.6 on 2026-06-12 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_is_accountant_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email2',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='El correo electrónico debe pertenecer al dominio @sena.edu.co o @soy.sena.edu.co', regex='^[a-zA-Z0-9._%+-]+@(soy\\.)?sena\\.edu\\.co$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_tel2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
