# Generated by Django 6.0.6 on 2026-07-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_user_email2_alter_users_user_tel2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
