# Generated by Django 6.0.6 on 2026-07-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('listar_usuarios', 'Listar usuarios'), ('generar_reporte_usuarios', 'Generar reporte usuarios')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='users',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
