# Generated by Django 6.0.6 on 2026-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_alter_users_options_users_last_heartbeat_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('user_document_type', 'user_document'), name='usuario_documento_unico_por_tipo'),
        ),
    ]
