# Generated by Django 6.0.6 on 2026-06-28 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0005_returnable_model_serial_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(limit_choices_to={'is_accountant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='identity_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_token',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('loan_students_group', models.CharField(max_length=7)),
                ('loan_justification', models.TextField()),
                ('loan_type', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10)),
                ('loan_date_out', models.DateField()),
                ('loan_date_in', models.DateField()),
                ('loan_status', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('devolucion_parcial', 'Devolución parcial'), ('pendiente', 'Pendiente')], default='activo', max_length=20)),
                ('identity_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='loans.identitytoken')),
                ('loan_user_lender', models.ForeignKey(limit_choices_to={'is_accountant': True}, on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_lender', to=settings.AUTH_USER_MODEL)),
                ('loan_user_requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan',
                'permissions': [('listar_loan', 'Listar préstamos'), ('generar_reporte_loan', 'Generar reporte préstamos')],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_loaned', models.PositiveIntegerField()),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('consumable_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='materials.consumablematerial')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loan')),
                ('returnable_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='materials.returnablematerial')),
            ],
            options={
                'db_table': 'loan_item',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('consumable_material__isnull', False), ('returnable_material__isnull', True)), models.Q(('consumable_material__isnull', True), ('returnable_material__isnull', False)), _connector='OR'), name='loan_item_one_material_type')],
            },
        ),
    ]
