# Generated by Django 6.0.6 on 2026-07-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_add_en_espera_aceptacion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('listar_loan', 'Listar préstamos'), ('generar_reporte_loan', 'Generar reporte préstamos')], 'verbose_name': 'préstamo', 'verbose_name_plural': 'préstamos'},
        ),
        migrations.RenameField(
            model_name='identitytoken',
            old_name='is_confirmed',
            new_name='lender_confirmed',
        ),
        migrations.AddField(
            model_name='identitytoken',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_tokens_as_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identitytoken',
            name='requester_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
