# Generated by Django 6.0.6 on 2026-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reminder_previo_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_vence_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
