# Generated by Django 6.0.6 on 2026-08-08 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_reminder_previo_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoken',
            name='requester_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='loan',
            name='requester_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='identitytoken',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_students_group',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_user_lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_lender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_user_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loan_user_requester__isnull', False), ('requester_email', '')), models.Q(('loan_user_requester__isnull', True), models.Q(('requester_email', ''), _negated=True)), _connector='OR'), name='loan_requester_registrado_o_correo'),
        ),
    ]
