export { fileSchema } from "./schemas/fileSchema.js";
export { default as Input } from "./components/Input.jsx";
export { default as Button } from "./components/Button.jsx";
export { default as IconButton } from "./components/IconButton.jsx";
export { default as DateInput } from "./components/DateInput.jsx";
export { default as Select } from "./components/Select.jsx";
export { default as Checkbox } from "./components/Checkbox.jsx";
export { IconButtonReal } from "./components/IconButtonReal.jsx";
export { default as StatusSwitch } from "./components/StatusSwitch.jsx";
export { default as ViewPageTemplate } from "./components/ViewPageTemplate.jsx";
export { default as ViewDetailCard } from "./components/ViewDetailCard.jsx";
export { Dropdown, DropdownContent, DropdownItem, DropdownTrigger } from "./components/Dropdown.jsx";
export { default as Textarea } from "./components/TextArea.jsx";
export { default as FileInput } from "./components/FileInput.jsx";
export { default as TechnicalFilesInput } from "./components/TechnicalFilesInput.jsx";
export { default as TechnicalFilesModal } from "./components/TechnicalFilesModal.jsx";
export { default as MultiSelect } from "./components/MultiSelect.jsx";
export { default as Modal } from "./components/Modal.jsx";
export { default as AuthLayout } from "./layouts/AuthLayout.jsx";
export { default as Navbar } from "./layouts/Navbar.jsx";
export { default as Header } from "./layouts/Header.jsx";
export { default as SearchField } from "./components/SerchField.jsx";
export { default as DashboardLayout } from "./layouts/DashboardLayout.jsx";
export { default as Carousel } from "./components/Carousel.jsx";
export { default as ProtectedRoute } from "./components/auth/ProtectedRoute.jsx";
export { Alert, TIMER } from "./components/utils/alert.js";
//Exporta layout y components
