"""
Django settings for backend_sigi project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%!r22(3^$t_f_w05d*9#0x=i#!0s!$tv$0k^obopt7a-mrt@@a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'backend_sigi.modules.users',
    'backend_sigi.modules.materials',
    'backend_sigi.modules.loans',
    'backend_sigi.modules.tasks',
    'backend_sigi.modules.inventory_name',
    'backend_sigi.modules.category',
    'backend_sigi.modules.quotation',
    'backend_sigi.modules.audit',
    'corsheaders',
]
AUTH_USER_MODEL = 'users.Users' #Para usar el models de users propio
#filtro para la validacion de cambio de contraseña, despues django usa el auth normal
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# TIME_ZONE se define más abajo, en la sección de Internationalization.
# Antes estaba declarado aquí también y la definición de abajo lo sobrescribía.
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_sigi.api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_sigi.api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', '5432'),

        # Se usa el TRANSACTION POOLER de Supabase (puerto 6543), no el de
        # sesión (5432).
        #
        # Reutiliza la conexión hasta 10 minutos. Medido contra esta base:
        # abrir una conexión cuesta ~1,8 s (la base está en us-east-1), y las
        # consultas en sí menos de 1 s. Con CONN_MAX_AGE = 0 cada petición
        # pagaba esos 1,8 s por separado, así que una pantalla con 14
        # peticiones perdía unos 25 segundos solo en conectar.
        #
        # Mantener la conexión abierta es seguro precisamente por usar el
        # pooler de TRANSACCIONES: está hecho para muchos clientes conectados
        # de forma persistente, multiplexados sobre pocas conexiones reales.
        # Con el pooler de SESIÓN (5432) esto sí agotaría el cupo, porque allí
        # cada cliente ocupa una conexión real del servidor.
        'CONN_MAX_AGE': 600,

        # Comprueba que la conexión guardada siga viva antes de reutilizarla.
        # Sin esto, una conexión cerrada por el otro extremo hace fallar la
        # petición con "server closed the connection unexpectedly".
        'CONN_HEALTH_CHECKS': True,

        'OPTIONS': {
            'sslmode': 'require',  # Supabase requiere SSL

            # Sin límite explícito, psycopg2 puede quedarse esperando decenas
            # de segundos cuando el pooler no responde
            'connect_timeout': 10,
        },
    }
}

# Obligatorio al usar un pooler en modo transacción: en ese modo la conexión
# cambia de sesión entre consultas, y los cursores del lado del servidor
# (que Django usa en iterator()) dejan de ser válidos.
DISABLE_SERVER_SIDE_CURSORS = True

SUPABASE_URL = os.getenv('SUPABASE_URL', '')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY', '')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Zona horaria de Colombia (UTC-5). NO cambiar a 'UTC': con UTC, a partir de
# las 7:00 p.m. hora local el servidor ya considera que es el día siguiente,
# lo que hacía que un préstamo que vence mañana se reportara como "vence hoy".
# Afecta a timezone.localdate(), los logs de auditoría y las fechas que se
# muestran en el sistema.
TIME_ZONE = 'America/Bogota'

USE_I18N = True

# Las fechas se guardan en UTC en la base de datos y Django las convierte
# a TIME_ZONE al leerlas. Por eso basta con corregir TIME_ZONE.
USE_TZ = True
# API sin estados, en cada peticion fornt, debe enviar un token
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'backend_sigi.modules.users.backends.JWTSessionAuthentication',
    ),
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=1)
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',   # host de react
]

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Cache
# En desarrollo usa memoria local; en producción configurar Redis con REDIS_URL
REDIS_URL = os.getenv("REDIS_URL", "")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Brevo SMTP - envío de correos transaccionales
EMAIL_BACKEND = (
    'backend_sigi.api.email_backend.BrevoEmailBackend'  # ignora SSL — solo desarrollo
    if DEBUG else
    'django.core.mail.backends.smtp.EmailBackend'       # verificación SSL estándar — producción
)
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('BREVO_SMTP_LOGIN', '')
EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_KEY', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'sigi.sena@gmail.com')

# ──────────────────────────────────────────────────────────────
# Auditoría — registro de acciones de usuarios
#
# Vive en la tabla audit_log (ver modules/audit/models.py). Antes era un
# archivo rotado a diario en backend_sigi/logs/, pero se perdía en los
# despliegues y la rotación chocaba entre los dos procesos que levanta el
# autoreloader en Windows.
#
# La purga de registros viejos la hace el comando purgar_auditoria.
# ──────────────────────────────────────────────────────────────
