# Generated by Django 6.0.6 on 2026-06-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablematerial',
            name='material_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
