# Generated by Django 6.0.6 on 2026-06-17 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_consumablematerial_material_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=150)),
                ('material_description', models.TextField()),
                ('material_barcode_sena', models.CharField(blank=True, max_length=100, null=True)),
                ('material_quantity', models.PositiveIntegerField()),
                ('material_quantity_loaned', models.PositiveIntegerField(default=0)),
                ('material_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_location', models.CharField(blank=True, default='', max_length=200)),
                ('material_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_state', models.CharField(blank=True, choices=[('no_disponible', 'No disponible'), ('prestado', 'Prestado'), ('traslado', 'Traslado'), ('baja', 'Baja')], max_length=20, null=True)),
                ('material_model', models.CharField(max_length=150)),
                ('material_serial', models.CharField(max_length=150)),
                ('material_category', models.CharField(choices=[('herramienta', 'Herramienta'), ('maquinaria_equipos', 'Maquinaria y equipos'), ('muebles_enseres', 'Muebles y enseres')], max_length=20)),
                ('material_dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='materials.brand')),
                ('inventory_manager', models.ForeignKey(limit_choices_to={'is_accountant': True}, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'returnable_material',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_files', to='materials.returnablematerial')),
            ],
            options={
                'db_table': 'technical_sheet_file',
            },
        ),
    ]
