# Generated by Django 6.0.6 on 2026-06-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_returnablematerial_technicalsheetfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': [('listar_brand', 'Listar marcas'), ('generar_reporte_brand', 'Generar reporte marcas')]},
        ),
        migrations.AlterModelOptions(
            name='consumablematerial',
            options={'permissions': [('listar_consumablematerial', 'Listar material de consumo'), ('generar_reporte_consumablematerial', 'Generar reporte material de consumo')]},
        ),
        migrations.AlterModelOptions(
            name='returnablematerial',
            options={'permissions': [('listar_returnablematerial', 'Listar material devolutivo'), ('generar_reporte_returnablematerial', 'Generar reporte material devolutivo')]},
        ),
    ]
