# Generated by Django 6.0.6 on 2026-08-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_returnable_model_serial_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': [('listar_brand', 'Listar marcas'), ('generar_reporte_brand', 'Generar reporte marcas')], 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='consumablematerial',
            options={'permissions': [('listar_consumablematerial', 'Listar material de consumo'), ('generar_reporte_consumablematerial', 'Generar reporte material de consumo')], 'verbose_name': 'material de consumo', 'verbose_name_plural': 'materiales de consumo'},
        ),
        migrations.AlterModelOptions(
            name='returnablematerial',
            options={'permissions': [('listar_returnablematerial', 'Listar material devolutivo'), ('generar_reporte_returnablematerial', 'Generar reporte material devolutivo')], 'verbose_name': 'material devolutivo', 'verbose_name_plural': 'materiales devolutivos'},
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='material_model',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='consumablematerial',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='materials.brand'),
        ),
        migrations.AlterField(
            model_name='returnablematerial',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='materials.brand'),
        ),
    ]
