# Generated by Django 6.0.6 on 2026-08-01 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_brand_options_alter_consumablematerial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablematerial',
            name='inventory_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_accountant': True}, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='material_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='material_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='material_serial',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returnablematerial',
            name='inventory_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_accountant': True}, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnablematerial',
            name='material_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnablematerial',
            name='material_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalsheetfile',
            name='consumable_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_files', to='materials.consumablematerial'),
        ),
        migrations.AlterField(
            model_name='consumablematerial',
            name='inventory_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_accountant': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnablematerial',
            name='inventory_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_accountant': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicalsheetfile',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_files', to='materials.returnablematerial'),
        ),
        migrations.AddConstraint(
            model_name='technicalsheetfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumable_material__isnull', True), ('material__isnull', False)), models.Q(('consumable_material__isnull', False), ('material__isnull', True)), _connector='OR'), name='technical_sheet_one_material_type'),
        ),
    ]
