# Generated by Django 6.0.6 on 2026-08-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_consumablematerial_inventory_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablematerial',
            name='inventory_manager',
        ),
        migrations.RemoveField(
            model_name='returnablematerial',
            name='inventory_manager',
        ),
    ]
