# Generated by Django 6.0.6 on 2026-08-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('inventory_name', '0001_initial'),
        ('materials', '0008_remove_consumablematerial_inventory_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnablematerial',
            old_name='material_category',
            new_name='material_type',
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='category.category'),
        ),
        migrations.AddField(
            model_name='consumablematerial',
            name='inventory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='inventory_name.inventoryname'),
        ),
        migrations.AddField(
            model_name='returnablematerial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='category.category'),
        ),
        migrations.AddField(
            model_name='returnablematerial',
            name='inventory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='inventory_name.inventoryname'),
        ),
    ]
