# Generated by Django 6.0.6 on 2026-08-07 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_rename_material_category_returnablematerial_material_type_and_more'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_links', to='materials.consumablematerial')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_links', to='materials.returnablematerial')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_links', to='quotation.quotation')),
            ],
            options={
                'verbose_name': 'cotización de material',
                'verbose_name_plural': 'cotizaciones de material',
                'db_table': 'material_quotation',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('consumable_material__isnull', True), ('material__isnull', False)), models.Q(('consumable_material__isnull', False), ('material__isnull', True)), _connector='OR'), name='material_quotation_one_material_type'), models.UniqueConstraint(fields=('quotation', 'material'), name='material_quotation_unica_devolutivo'), models.UniqueConstraint(fields=('quotation', 'consumable_material'), name='material_quotation_unica_consumo')],
            },
        ),
    ]
