# Generated by Django 6.0.6 on 2026-08-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_materialquotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialquotation',
            options={'default_permissions': ()},
        ),
    ]
