# Generated by Django 6.0.6 on 2026-09-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
    ]
