# Generated by Django 6.0.6 on 2026-08-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'nombre de inventario',
                'verbose_name_plural': 'nombres de inventario',
                'db_table': 'inventory_name',
                'permissions': [('listar_inventoryname', 'Listar nombres de inventario')],
            },
        ),
    ]
